### ISSUE TITLE
Deprecated features used!

### ISSUE THREAD

**Issue by wokamoto** [Launch-with-1-Click/lw1-amimoto#42]
```
Deprecated features used!
  "method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 4 locations:
    - /tmp/chef-solo/cookbooks/amimoto/recipes/default.rb:51:in `from_file'
    - /tmp/chef-solo/cookbooks/amimoto/recipes/phpmyadmin.rb:2:in `from_file'
    - (erubis):292:in `block in evaluate'
    - (erubis):317:in `block in evaluate'
```

**Comment by wokamoto** [comment]
これだけ残ったけど、とりあえずこの issue はクローズします

```
Deprecated features used!
  method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 2 locations:
    - (erubis):292:in `block in evaluate'
    - (erubis):317:in `block in evaluate'
```
